#==============================================================================
# Requirements
# * Docker installed
# * docker-compose installed
#----------------------------------------------------------------------
# Use
# UID=${UID} GID=${GID} docker-compose -f docker-compose-dev.yml up -d
#----------------------------------------------------------------------
version: '3.8'
#----------------------------------------------------------------------
# Networks
#----------------------------------------------------------------------
networks:
  tech-challenge-products-catalog-net:
    driver: bridge
#----------------------------------------------------------------------
# Volumes
#----------------------------------------------------------------------
volumes:
  tech-challenge-products-catalog-db-data: {}
#----------------------------------------------------------------------
# Services:
#----------------------------------------------------------------------
services:
  tech-challenge-products-catalog:
    image: node:16-bullseye
    container_name: tech-challenge-products-catalog
    working_dir: /usr/src/app
    command: /usr/src/app/docker/docker-run-dev.sh
    user: '${DUID}:${DGID}'
    volumes:
      - '..:/usr/src/app:Z'
    ports:
      - '3000:3000'
    networks:
      - tech-challenge-products-catalog-net
    env_file:
      - ./dev-local.env
    depends_on:
      - tech-challenge-products-catalog-db
  tech-challenge-products-catalog-db:
    image: postgres:latest
    container_name: tech-challenge-products-catalog-db
    ports:
      - 5432:5432
    networks:
      - tech-challenge-products-catalog-net
    env_file:
      - ./dev-local.env
    volumes:
      - tech-challenge-products-catalog-db-data:/var/lib/postgresql/data
