#==============================================================================
# Requirements
# * Docker installed
# * docker-compose installed
#----------------------------------------------------------------------
# Use
# UID=${UID} GID=${GID} docker-compose -f docker-compose-dev.yml up -d
#----------------------------------------------------------------------
version: '3.8'
#----------------------------------------------------------------------
# Networks
#----------------------------------------------------------------------
networks:
  tech-challenge-payment-net:
    driver: bridge
#----------------------------------------------------------------------
# Volumes
#----------------------------------------------------------------------
volumes:
  tech-challenge-payment-db-data: {}
#----------------------------------------------------------------------
# Services:
#----------------------------------------------------------------------
services:
  tech-challenge-payment:
    image: node:16-bullseye
    container_name: tech-challenge-payment
    working_dir: /usr/src/app
    command: /usr/src/app/docker/docker-run-dev.sh
    user: '${DUID}:${DGID}'
    volumes:
      - '..:/usr/src/app:Z'
    ports:
      - '3000:3000'
    networks:
      - tech-challenge-payment-net
    env_file:
      - ./dev-local.env
    depends_on:
      - tech-challenge-payment-db
  tech-challenge-payment-db:
    image: postgres:latest
    container_name: tech-challenge-payment-db
    ports:
      - 5432:5432
    networks:
      - tech-challenge-payment-net
    env_file:
      - ./dev-local.env
    volumes:
      - tech-challenge-payment-db-data:/var/lib/postgresql/data
  localstack:
    image: 'localstack/localstack:latest'
    container_name: localstack
    ports:
      - '4566:4566'
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-/var/lib/localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack/sqs:/etc/localstack/init/ready.d
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sns
    networks:
      - tech-challenge-payment-net
